### ISSUE TITLE
failed to build in ubuntu 20.04

### ISSUE THREAD

**Issue by ProjectPatatoe** [openweave/openweave-core#694]
Error when compiling 
```
In file included from ../../src/include/Weave/Profiles/security/WeaveSecurity.h:31,
                 from ../../src/include/Weave/Core/WeaveFabricState.h:49,
                 from ../../src/include/Weave/Core/WeaveCore.h:57,
                 from ../../src/include/Warm/Warm.h:80,
                 from /home/patatoe/Desktop/eclipse/openweave-core/src/warm/../../src/warm/WarmCore.cpp:26:
../../src/include/Weave/Support/ASN1.h:123:28: error: ‘OID’ has not been declared
```
Ubuntu 20.04.5 LTS

I was able to install everything for `./configure` to be satisfied
